# 用户画像系统配置文件

# 系统配置
system:
  data_path: "data/"
  output_path: "output/profiles/"
  log_level: "INFO"
  max_workers: 4

# 特征106: 兴趣标签配置
interest_tags:
  max_tags: 10                    # 最大标签数量
  min_frequency: 3                # 最小出现频次
  decay_factor: 0.95              # 时间衰减因子
  categories:
    entertainment: [100, 101, 102]  # 娱乐类物品特征
    technology: [111, 112, 113]     # 科技类物品特征
    lifestyle: [114, 115, 116]      # 生活类物品特征
    business: [117, 118, 119]       # 商业类物品特征
    education: [120, 121, 122]      # 教育类物品特征

# 特征107: 行为偏好配置
behavior_preferences:
  max_preferences: 8              # 最大偏好数量
  time_windows: [1, 7, 30]        # 时间窗口(天)
  preference_types:
    click_frequency: "点击频率偏好"
    dwell_time: "停留时间偏好"
    interaction_pattern: "交互模式偏好"
    time_preference: "时间偏好"
    device_preference: "设备偏好"
    category_preference: "类别偏好"

# 特征108: 活跃度等级配置
activity_levels:
  levels: 4                       # 4个等级
  metrics:
    daily_actions: [0, 5, 15, 30]     # 每日行为次数阈值
    session_duration: [0, 300, 900, 1800]  # 会话时长阈值(秒)
    frequency: [0, 3, 7, 14]           # 访问频率阈值(天)
    engagement_score: [0, 0.3, 0.6, 0.8]  # 参与度分数阈值

# 特征110: 用户类型配置
user_types:
  types: 2                        # 2个类型
  criteria:
    type_0:                       # 轻度用户
      min_sessions: 1
      max_actions: 10
      max_dwell_time: 60
    type_1:                       # 重度用户
      min_sessions: 5
      min_actions: 20
      min_dwell_time: 120

# 实时更新配置
real_time_update:
  update_interval: 300            # 更新间隔(秒)
  batch_size: 1000               # 批处理大小
  queue_size: 10000              # 事件队列大小
  cache_size: 500                # 用户行为缓存大小

# 定时更新配置
scheduled_update:
  hourly_update: true             # 是否启用每小时更新
  daily_deep_update: "02:00"      # 每日深度更新时间
  weekly_full_update: "sunday:03:00"  # 每周全量更新时间
  health_check_interval: 5        # 健康检查间隔(分钟)

# 数据源配置
data_sources:
  kafka:
    enabled: false
    bootstrap_servers: ["localhost:9092"]
    topic: "user_behavior"
    group_id: "profile_updater"
  
  database:
    enabled: false
    host: "localhost"
    port: 5432
    database: "user_behavior"
    username: "user"
    password: "password"
  
  file:
    enabled: true
    path: "data/seq.jsonl"
    format: "jsonl"

# 监控配置
monitoring:
  enable_metrics: true            # 是否启用指标收集
  metrics_interval: 60            # 指标收集间隔(秒)
  alert_thresholds:
    low_confidence: 0.3           # 低置信度告警阈值
    low_freshness: 0.7            # 低新鲜度告警阈值
    high_error_rate: 0.05         # 高错误率告警阈值
  
  reporting:
    enable_console: true          # 控制台报告
    enable_file: true             # 文件报告
    report_interval: 3600         # 报告间隔(秒)
    report_path: "output/reports/"

# 特征工程配置
feature_engineering:
  # 时间特征
  time_features:
    hour_of_day: true             # 小时特征
    day_of_week: true             # 星期特征
    is_weekend: true              # 周末特征
  
  # 序列特征
  sequence_features:
    max_length: 100               # 最大序列长度
    min_length: 5                 # 最小序列长度
    window_size: 10               # 滑动窗口大小
  
  # 统计特征
  statistical_features:
    mean_dwell_time: true         # 平均停留时间
    std_dwell_time: true          # 停留时间标准差
    click_rate: true              # 点击率
    conversion_rate: true         # 转化率

# 模型配置
model:
  # 兴趣标签模型
  interest_model:
    algorithm: "tfidf"            # 算法类型
    max_features: 1000            # 最大特征数
    min_df: 2                     # 最小文档频率
  
  # 行为偏好模型
  behavior_model:
    algorithm: "clustering"       # 算法类型
    n_clusters: 8                 # 聚类数量
    random_state: 42              # 随机种子
  
  # 活跃度模型
  activity_model:
    algorithm: "threshold"        # 算法类型
    thresholds: [0.25, 0.5, 0.75] # 阈值

# 存储配置
storage:
  # 本地存储
  local:
    enabled: true
    path: "output/profiles/"
    format: "pickle"              # 存储格式: pickle, json
  
  # 数据库存储
  database:
    enabled: false
    host: "localhost"
    port: 5432
    database: "user_profiles"
    table: "profiles"
  
  # 分布式存储
  distributed:
    enabled: false
    type: "redis"                 # 存储类型: redis, memcached
    host: "localhost"
    port: 6379
    db: 0

# 性能配置
performance:
  # 内存配置
  memory:
    max_cache_size: 10000         # 最大缓存大小
    gc_interval: 3600             # 垃圾回收间隔(秒)
  
  # 并发配置
  concurrency:
    max_threads: 8                # 最大线程数
    max_processes: 4              # 最大进程数
  
  # 批处理配置
  batch_processing:
    batch_size: 1000              # 批处理大小
    timeout: 300                  # 超时时间(秒)


